// Generated by CoffeeScript 1.6.3
/*
    custom actano reporter
*/


(function() {
  var Sternchen, exports;

  require('chai').Assertion.includeStack = true;

  exports = module.exports = Sternchen;

  Sternchen = (function() {
    function Sternchen(runner) {
      this.runner = runner;
      this.n = 1;
      this.passes = 0;
      this.failures = 0;
      this.initalizeEvents();
    }

    Sternchen.prototype.initalizeEvents = function() {
      var _this = this;
      this.runner.on('start', function() {
        var total;
        total = _this.runner.grepTotal(_this.runner.suite);
        return console.log('%d..%d', 1, total);
      });
      this.runner.on('test end', function() {
        return ++_this.n;
      });
      this.runner.on('pending', function(test) {
        return console.log('ok %d %s # SKIP -', _this.n, _this.title(test));
      });
      this.runner.on('pass', function(test) {
        _this.passes++;
        return console.log('ok %d %s', _this.n, _this.title(test));
      });
      this.runner.on('fail', function(test, err) {
        _this.failures++;
        console.log('not ok %d %s', n, _this.title(test));
        if (err.stack) {
          return console.log(err.stack.replace(/^/gm, '  '));
        }
      });
      return runner.on('end', function() {
        console.log('# tests ' + (_this.passes + _this.failures));
        console.log('# pass ' + _this.passes);
        return console.log('# fail ' + _this.failures);
      });
    };

    Sternchen.prototype.title = function(test) {
      return test.parent.fullTitle() + " : " + test.title;
    };

    return Sternchen;

  })();

}).call(this);
